name = "dark"
background_color = "#1e1e2e"
text_color = "#cdd6f4"
selected_background_color = "#89b4fa"
selected_text_color = "#1e1e2e"
border_color = "#585b70"
border_width = 2.0
border_radius = 8.0
padding = 12.0
